import React, { useState, useMemo } from 'react';
import { 
  Database, 
  Layers, 
  Table, 
  Plus, 
  Search, 
  Copy, 
  Check, 
  CheckCircle, 
  AlertCircle, 
  HelpCircle, 
  Activity, 
  FileText, 
  Lock, 
  Unlock, 
  Play, 
  Send, 
  RefreshCw, 
  Users, 
  Folder, 
  GitCommit, 
  ShieldCheck,
  ChevronRight,
  Code,
  Sparkles
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import Dashboard from './components/Dashboard';
import { 
  TABLES, 
  INITIAL_USERS, 
  INITIAL_PROJECTS, 
  INITIAL_REQUIREMENTS, 
  INITIAL_USER_STORIES, 
  INITIAL_ACCEPTANCE_CRITERIA, 
  INITIAL_AUDIT_RESULTS, 
  INITIAL_QUESTIONS, 
  INITIAL_PRD_DOCS, 
  INITIAL_VERSION_HISTORY,
  TableSchema,
  UserRow,
  ProjectRow,
  RequirementRow,
  UserStoryRow,
  AcceptanceCriterionRow,
  AuditResultRow,
  ClarificationQuestionRow,
  PrdDocumentRow,
  VersionHistoryRow
} from './data';

export default function App() {
  // viewMode: 'agent' (Multi-Agent Requirements Workspace) | 'schema' (Postgres Schema Explorer)
  const [viewMode, setViewMode] = useState<'agent' | 'schema'>('agent');

  // Navigation Tabs for Schema Explorer: 'ddl' | 'explorer' | 'ledger' | 'checklist'
  const [activeTab, setActiveTab] = useState<'ddl' | 'explorer' | 'ledger' | 'checklist'>('explorer');
  
  // Selected Table inside Explorer
  const [selectedTableName, setSelectedTableName] = useState<string>('requirements');

  // Search filter for SQL text
  const [sqlSearch, setSqlSearch] = useState<string>('');

  // Local Reactive States simulating the live Postgres Database
  const [users, setUsers] = useState<UserRow[]>(INITIAL_USERS);
  const [projects, setProjects] = useState<ProjectRow[]>(INITIAL_PROJECTS);
  const [requirements, setRequirements] = useState<RequirementRow[]>(INITIAL_REQUIREMENTS);
  const [userStories, setUserStories] = useState<UserStoryRow[]>(INITIAL_USER_STORIES);
  const [criteria, setCriteria] = useState<AcceptanceCriterionRow[]>(INITIAL_ACCEPTANCE_CRITERIA);
  const [auditResults, setAuditResults] = useState<AuditResultRow[]>(INITIAL_AUDIT_RESULTS);
  const [questions, setQuestions] = useState<ClarificationQuestionRow[]>(INITIAL_QUESTIONS);
  const [prdDocs, setPrdDocs] = useState<PrdDocumentRow[]>(INITIAL_PRD_DOCS);
  const [versions, setVersions] = useState<VersionHistoryRow[]>(INITIAL_VERSION_HISTORY);

  // General Notification Alert Toast
  const [toastMessage, setToastMessage] = useState<string | null>(null);
  const [toastType, setToastType] = useState<'success' | 'info'>('success');

  const showToast = (message: string, type: 'success' | 'info' = 'success') => {
    setToastMessage(message);
    setToastType(type);
    setTimeout(() => {
      setToastMessage(null);
    }, 4000);
  };

  // State for insertion dialog input values
  const [userForm, setUserForm] = useState({ email: '', fullName: '', role: 'Business Analyst' });
  const [projectForm, setProjectForm] = useState({ name: '', description: '', userId: INITIAL_USERS[0].id, industryStandard: 'Krungsri Nimble Baseline' });
  const [reqForm, setReqForm] = useState({ epicName: '', projectId: INITIAL_PROJECTS[0].id });
  const [storyForm, setStoryForm] = useState({ requirementId: INITIAL_REQUIREMENTS[0].id, storyTitle: '', ticketCode: 'US-PAY-100', asA: '', iWantTo: '', soThat: '', criteriaText: '' });

  // Snapshot Creation state
  const [snapshotForm, setSnapshotForm] = useState({
    requirementId: INITIAL_REQUIREMENTS[0].id,
    authorId: INITIAL_USERS[0].id,
    changeDescription: 'Verified system boundaries and secured regulatory OTP flows.'
  });

  // State for SQL viewer scroll highlights
  const [copiedSql, setCopiedSql] = useState<boolean>(false);

  // Trigger Schema lock
  const [isSchemaLocked, setIsSchemaLocked] = useState<boolean>(true);

  // Inline Question answer helper
  const [resolvingQuestionId, setResolvingQuestionId] = useState<string | null>(null);
  const [answerInput, setAnswerInput] = useState<string>('');

  // Search keyword in datagrid
  const [gridSearch, setGridSearch] = useState<string>('');

  // Selected table schema object
  const activeTableSchema = useMemo(() => {
    return TABLES.find(t => t.name === selectedTableName) || TABLES[0];
  }, [selectedTableName]);

  // Full SQL Text computed for presentation
  const fullSqlText = `-- =========================================================================\n-- ENTERPRISE CORE BANKING REQUIREMENTS ENGINEERING DATABASE SCHEMAS\n-- TARGET PLATFORM: SUPABASE POSTGRESQL V15+\n-- GENERATED BY: Enterprise Requirements Architecture System\n-- =========================================================================\n\nCREATE EXTENSION IF NOT EXISTS "uuid-ossp";\n\n-- Automated update timestamp function\nCREATE OR REPLACE FUNCTION set_updated_at()\nRETURNS TRIGGER AS $$\nBEGIN\n    NEW.updated_at = NOW();\n    RETURN NEW;\nEND;\n$$ LANGUAGE plpgsql;\n\n-- 1. USERS TABLE\nCREATE TABLE users (\n    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n    email VARCHAR(255) UNIQUE NOT NULL,\n    full_name VARCHAR(255) NOT NULL,\n    role VARCHAR(50) NOT NULL,\n    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()\n);\n\n-- 2. PROJECTS TABLE\nCREATE TABLE projects (\n    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n    user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,\n    name VARCHAR(255) NOT NULL,\n    description TEXT,\n    industry_standard VARCHAR(100) NOT NULL,\n    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()\n);\n\n-- 3. REQUIREMENTS (EPICS) TABLE\nCREATE TABLE requirements (\n    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n    epic_name VARCHAR(255) NOT NULL,\n    total_user_stories INT NOT NULL DEFAULT 0,\n    current_version INT NOT NULL DEFAULT 1,\n    is_locked BOOLEAN NOT NULL DEFAULT FALSE,\n    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()\n);\n\n-- 4. USER STORIES TABLE\nCREATE TABLE user_stories (\n    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n    requirement_id UUID NOT NULL REFERENCES requirements(id) ON DELETE CASCADE,\n    ticket_code VARCHAR(50) NOT NULL UNIQUE,\n    story_title VARCHAR(255) NOT NULL,\n    as_a TEXT NOT NULL,\n    i_want_to TEXT NOT NULL,\n    so_that TEXT NOT NULL,\n    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()\n);\n\n-- 5. ACCEPTANCE CRITERIA TABLE\nCREATE TABLE acceptance_criteria (\n    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n    user_story_id UUID NOT NULL REFERENCES user_stories(id) ON DELETE CASCADE,\n    criteria_text TEXT NOT NULL,\n    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()\n);\n\n-- 6. AUDIT RESULTS TABLE\nCREATE TABLE audit_results (\n    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n    requirement_id UUID NOT NULL REFERENCES requirements(id) ON DELETE CASCADE,\n    version_reviewed INT NOT NULL,\n    is_valid BOOLEAN NOT NULL DEFAULT FALSE,\n    passed_checks JSONB NOT NULL DEFAULT '[]'::jsonb,\n    failed_checks JSONB NOT NULL DEFAULT '[]'::jsonb,\n    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()\n);\n\n-- 7. CLARIFICATION QUESTIONS TABLE\nCREATE TABLE clarification_questions (\n    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n    audit_result_id UUID NOT NULL REFERENCES audit_results(id) ON DELETE CASCADE,\n    checklist_category VARCHAR(100) NOT NULL,\n    target_user_story_id UUID REFERENCES user_stories(id) ON DELETE SET NULL,\n    question_text TEXT NOT NULL,\n    user_answer TEXT,\n    is_resolved BOOLEAN NOT NULL DEFAULT FALSE,\n    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()\n);\n\n-- 8. PRD DOCUMENTS TABLE\nCREATE TABLE prd_documents (\n    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n    version INT NOT NULL,\n    markdown_content TEXT NOT NULL,\n    mermaid_graph TEXT,\n    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()\n);\n\n-- 9. VERSION HISTORY & SNAPSHOT LEDGER\nCREATE TABLE version_history (\n    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n    requirement_id UUID NOT NULL REFERENCES requirements(id) ON DELETE CASCADE,\n    version_number INT NOT NULL,\n    changed_by_user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,\n    change_description TEXT NOT NULL,\n    state_snapshot JSONB NOT NULL,\n    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()\n);\n\n-- FOREIGN KEY AND COMPLIANCE INDEXES\nCREATE INDEX idx_projects_user_id ON projects(user_id);\nCREATE INDEX idx_requirements_project_id ON requirements(project_id);\nCREATE INDEX idx_user_stories_requirement_id ON user_stories(requirement_id);\nCREATE INDEX idx_acceptance_criteria_user_story_id ON acceptance_criteria(user_story_id);\nCREATE INDEX idx_audit_results_requirement_id ON audit_results(requirement_id);\nCREATE INDEX idx_clarification_questions_audit_result_id ON clarification_questions(audit_result_id);\nCREATE INDEX idx_prd_documents_project_id ON prd_documents(project_id);\nCREATE INDEX idx_version_history_project_id ON version_history(project_id);\nCREATE INDEX idx_version_history_requirement_id ON version_history(requirement_id);\nCREATE INDEX idx_version_history_changed_by_user_id ON version_history(changed_by_user_id);\nCREATE INDEX idx_users_role ON users(role);\nCREATE INDEX idx_requirements_is_locked ON requirements(is_locked);\nCREATE INDEX idx_audit_results_is_valid ON audit_results(is_valid);\nCREATE INDEX idx_clarification_questions_is_resolved ON clarification_questions(is_resolved);\nCREATE INDEX idx_clarification_questions_category ON clarification_questions(checklist_category);`;

  // Filtered rows of SQL based on user search
  const sqlLines = useMemo(() => {
    const lines = fullSqlText.split('\n');
    if (!sqlSearch) return lines;
    return lines.map(line => {
      if (line.toLowerCase().includes(sqlSearch.toLowerCase())) {
        return { text: line, highlighted: true };
      }
      return { text: line, highlighted: false };
    });
  }, [sqlSearch]);

  const copySqlToClipboard = () => {
    navigator.clipboard.writeText(fullSqlText);
    setCopiedSql(true);
    showToast("PostgreSQL DDL script copied to clipboard!");
    setTimeout(() => setCopiedSql(false), 2000);
  };

  // Helper to retrieve user list or specific attributes
  const getUserName = (id: string) => {
    const u = users.find(x => x.id === id);
    return u ? u.full_name : 'Unknown User';
  };

  const getProjectName = (id: string) => {
    const p = projects.find(x => x.id === id);
    return p ? p.name : 'Unknown Project';
  };

  const getEpicName = (id: string) => {
    const r = requirements.find(x => x.id === id);
    return r ? r.epic_name : 'Unknown Epic';
  };

  // Filter Grid rows dynamically based on selectedTableName
  const filteredGridData = useMemo(() => {
    let raw: any[] = [];
    switch (selectedTableName) {
      case 'users': raw = users; break;
      case 'projects': raw = projects; break;
      case 'requirements': raw = requirements; break;
      case 'user_stories': raw = userStories; break;
      case 'acceptance_criteria': raw = criteria; break;
      case 'audit_results': raw = auditResults; break;
      case 'clarification_questions': raw = questions; break;
      case 'prd_documents': raw = prdDocs; break;
      case 'version_history': raw = versions; break;
    }
    if (!gridSearch) return raw;
    return raw.filter((row: any) => 
      JSON.stringify(row).toLowerCase().includes(gridSearch.toLowerCase())
    );
  }, [selectedTableName, gridSearch, users, projects, requirements, userStories, criteria, auditResults, questions, prdDocs, versions]);

  // Insert Simulated Database Record handler
  const handleInsertSimulatedRow = (e: React.FormEvent) => {
    e.preventDefault();
    const newId = crypto.randomUUID();
    const nowTimestamp = new Date().toISOString().replace('Z', '+00');

    let simulatedSql = '';

    if (selectedTableName === 'users') {
      if (!userForm.email || !userForm.fullName) {
        showToast("Error: Missing required fields email or full_name", "info");
        return;
      }
      const newRow: UserRow = {
        id: newId,
        email: userForm.email,
        full_name: userForm.fullName,
        role: userForm.role,
        created_at: nowTimestamp
      };
      setUsers([newRow, ...users]);
      simulatedSql = `INSERT INTO users (id, email, full_name, role, created_at, updated_at)\nVALUES ('${newId}', '${userForm.email}', '${userForm.fullName}', '${userForm.role}', NOW(), NOW());`;
      setUserForm({ email: '', fullName: '', role: 'Business Analyst' });

    } else if (selectedTableName === 'projects') {
      if (!projectForm.name) {
        showToast("Error: Missing project name", "info");
        return;
      }
      const newRow: ProjectRow = {
        id: newId,
        user_id: projectForm.userId,
        name: projectForm.name,
        description: projectForm.description,
        industry_standard: projectForm.industryStandard,
        created_at: nowTimestamp
      };
      setProjects([newRow, ...projects]);
      simulatedSql = `INSERT INTO projects (id, user_id, name, description, industry_standard, created_at)\nVALUES ('${newId}', '${projectForm.userId}', '${projectForm.name}', '${projectForm.description}', '${projectForm.industryStandard}', NOW());`;
      setProjectForm(prev => ({ ...prev, name: '', description: '' }));

    } else if (selectedTableName === 'requirements') {
      if (!reqForm.epicName) {
        showToast("Error: Epic name required", "info");
        return;
      }
      const newRow: RequirementRow = {
        id: newId,
        project_id: reqForm.projectId,
        epic_name: reqForm.epicName,
        total_user_stories: 0,
        current_version: 1,
        is_locked: false,
        created_at: nowTimestamp
      };
      setRequirements([newRow, ...requirements]);
      simulatedSql = `INSERT INTO requirements (id, project_id, epic_name, total_user_stories, current_version, is_locked, created_at)\nVALUES ('${newId}', '${reqForm.projectId}', '${reqForm.epicName}', 0, 1, FALSE, NOW());`;
      setReqForm(prev => ({ ...prev, epicName: '' }));

    } else if (selectedTableName === 'user_stories') {
      if (!storyForm.storyTitle || !storyForm.asA || !storyForm.iWantTo || !storyForm.soThat) {
        showToast("Error: Complete story parts (As a, I want to, So that)", "info");
        return;
      }
      // Check unique code
      if (userStories.some(s => s.ticket_code === storyForm.ticketCode)) {
        showToast(`Error: Ticket code ${storyForm.ticketCode} is already registered.`, "info");
        return;
      }

      const newStory: UserStoryRow = {
        id: newId,
        requirement_id: storyForm.requirementId,
        ticket_code: storyForm.ticketCode,
        story_title: storyForm.storyTitle,
        as_a: storyForm.asA,
        i_want_to: storyForm.iWantTo,
        so_that: storyForm.soThat,
        created_at: nowTimestamp
      };

      setUserStories([newStory, ...userStories]);

      // If they also added acceptance criteria text, insert that too
      if (storyForm.criteriaText.trim()) {
        const criteriaId = crypto.randomUUID();
        const newCriterion: AcceptanceCriterionRow = {
          id: criteriaId,
          user_story_id: newId,
          criteria_text: storyForm.criteriaText.trim(),
          created_at: nowTimestamp
        };
        setCriteria(prev => [newCriterion, ...prev]);
        simulatedSql = `BEGIN;\nINSERT INTO user_stories (id, requirement_id, ticket_code, story_title, as_a, i_want_to, so_that, created_at)\nVALUES ('${newId}', '${storyForm.requirementId}', '${storyForm.ticketCode}', '${storyForm.storyTitle}', '${storyForm.asA}', '${storyForm.iWantTo}', '${storyForm.soThat}', NOW());\n\nINSERT INTO acceptance_criteria (id, user_story_id, criteria_text, created_at)\nVALUES ('${criteriaId}', '${newId}', '${storyForm.criteriaText.replace(/'/g, "''")}', NOW());\nCOMMIT;`;
      } else {
        simulatedSql = `INSERT INTO user_stories (id, requirement_id, ticket_code, story_title, as_a, i_want_to, so_that, created_at)\nVALUES ('${newId}', '${storyForm.requirementId}', '${storyForm.ticketCode}', '${storyForm.storyTitle}', '${storyForm.asA}', '${storyForm.iWantTo}', '${storyForm.soThat}', NOW());`;
      }

      // Increment epic total count
      setRequirements(prev => prev.map(r => r.id === storyForm.requirementId ? { ...r, total_user_stories: r.total_user_stories + 1 } : r));

      setStoryForm({
        requirementId: INITIAL_REQUIREMENTS[0].id,
        storyTitle: '',
        ticketCode: 'US-PAY-' + Math.floor(100 + Math.random() * 900),
        asA: '',
        iWantTo: '',
        soThat: '',
        criteriaText: ''
      });
    }

    showToast(`Successfully Simulated! Record inserted into local state.`, "success");
    // Log virtual SQL to show enterprise transparency
    console.log("SIMULATED SQL INGRESS:\n", simulatedSql);
  };

  // Answer inline checklist clarification question
  const submitQuestionAnswer = (e: React.FormEvent, questionId: string) => {
    e.preventDefault();
    if (!answerInput.trim()) return;

    setQuestions(prev => prev.map(q => q.id === questionId ? { ...q, user_answer: answerInput.trim(), is_resolved: true } : q));
    setResolvingQuestionId(null);
    setAnswerInput('');
    showToast("Audit Clarification answer logged! Metric state updated.", "success");
  };

  // Count metrics
  const activeUnresolvedQuestionsCount = useMemo(() => {
    return questions.filter(q => !q.is_resolved).length;
  }, [questions]);

  const auditValidityScorePercent = useMemo(() => {
    const total = questions.length;
    if (total === 0) return 100;
    const resolved = questions.filter(q => q.is_resolved).length;
    return Math.round((resolved / total) * 100);
  }, [questions]);

  // Capture Version History Snapshot
  const handleCaptureSnapshot = (e: React.FormEvent) => {
    e.preventDefault();
    
    const relatedReq = requirements.find(r => r.id === snapshotForm.requirementId);
    if (!relatedReq) return;

    // Filter stories linked to this epic to create the immutable state snapshot
    const linkedStories = userStories.filter(s => s.requirement_id === relatedReq.id);
    const linkedStoriesSnap = linkedStories.map(s => {
      const relatedAc = criteria.filter(ac => ac.user_story_id === s.id);
      return {
        ticket: s.ticket_code,
        title: s.story_title,
        as_a: s.as_a,
        i_want_to: s.i_want_to,
        so_that: s.so_that,
        acceptance_criteria: relatedAc.map(a => a.criteria_text)
      };
    });

    const nextVersion = relatedReq.current_version + 1;
    const newSnapshotId = crypto.randomUUID();

    const newVersionLog: VersionHistoryRow = {
      id: newSnapshotId,
      project_id: relatedReq.project_id,
      requirement_id: relatedReq.id,
      version_number: nextVersion,
      changed_by_user_id: snapshotForm.authorId,
      change_description: snapshotForm.changeDescription,
      state_snapshot: JSON.stringify({
        captured_at: new Date().toISOString(),
        epic_name: relatedReq.epic_name,
        user_stories: linkedStoriesSnap
      }),
      created_at: new Date().toISOString().replace('Z', '+00')
    };

    // Update requirements state: increment version number
    setRequirements(prev => prev.map(r => r.id === relatedReq.id ? { ...r, current_version: nextVersion } : r));
    // Append to version ledger
    setVersions([newVersionLog, ...versions]);

    showToast(`Snapshot Captured! Mapped ${linkedStories.length} stories into immutable JSONB Ledger.`, "success");
  };

  // Toggle Single Epic Lock status
  const toggleEpicLock = (id: string) => {
    setRequirements(prev => prev.map(r => r.id === id ? { ...r, is_locked: !r.is_locked } : r));
    const isNowLocked = !requirements.find(r => r.id === id)?.is_locked;
    showToast(`Epic Requirement state is now ${isNowLocked ? 'LOCKED' : 'UNLOCKED'} for modification.`, "success");
  };

  return (
    <div id="app-container" className="w-full h-screen bg-slate-100 flex flex-col font-sans text-slate-800 antialiased overflow-hidden">
      
      {/* Dynamic Alert Banner/Toast */}
      <AnimatePresence>
        {toastMessage && (
          <motion.div 
            initial={{ opacity: 0, y: -50 }}
            animate={{ opacity: 1, y: 16 }}
            exit={{ opacity: 0, y: -50 }}
            className="fixed top-4 left-1/2 transform -translate-x-1/2 z-50 flex items-center gap-3 px-5 py-3 rounded-lg shadow-xl border bg-slate-900 border-slate-700 text-white max-w-md"
          >
            {toastType === 'success' ? (
              <div className="w-5 h-5 bg-emerald-500 rounded-full flex items-center justify-center text-slate-900">
                <Check className="w-3.5 h-3.5 stroke-[3]" />
              </div>
            ) : (
              <div className="w-5 h-5 bg-blue-500 rounded-full flex items-center justify-center text-slate-900">
                <AlertCircle className="w-3.5 h-3.5 stroke-[3]" />
              </div>
            )}
            <span className="text-sm font-medium">{toastMessage}</span>
          </motion.div>
        )}
      </AnimatePresence>

      {/* GLOBAL TOP NAVBAR (Matching Stitch Header precisely) */}
      <header className="h-16 w-full shrink-0 flex items-center justify-between px-6 bg-white border-b border-black/5 z-50">
        {/* Left: Branding & Project Title */}
        <div className="flex items-center gap-4 min-w-[280px]">
          <span className="material-symbols-outlined text-[#b45309] text-2xl font-bold">Agentic-AI</span>
          <div className="flex items-center cursor-pointer group">
            <h1 className="font-bold text-slate-900 text-sm">For PRD</h1>
          </div>
        </div>
        
        {/* Right actions: User Avatar */}
        <div className="w-8 h-8 rounded-full overflow-hidden cursor-pointer border border-[#b45309]/30">
            <img className="w-full h-full object-cover" referrerPolicy="no-referrer" src="https://lh3.googleusercontent.com/aida-public/AB6AXuBDlAC0DOS6EdgtoiiblRYSq4kovm0aGBgk0J0--3PR3DjY3GRR1MSXxugEHy6Z8hnEcHWXmlcYG_KCT2Tzf3RSjEJ_sS6mj0h8OhQRZXWOaNxhjNMAvrg3TB9jZP5Xf2rG1f_yqj9jQelGFRgrZyqoQuf34EIYP3Vkbvpkm0oruz-4pWwgPSZc9V3DcXA-qq_ufzqZc5GCob0H1QKqJcC7AAnES2wcw3fJ6hiY1iVgYEUWrmCkJbVe"/>
        </div>
      </header>

      {/* MAIN CONTAINER FRAME */}
      <div className="flex-1 flex overflow-hidden">
        {viewMode === 'agent' ? (
          <Dashboard />
        ) : (
          <>
            {/* ==========================================
                SIDEBAR NAVIGATION (Postgres Hub)
            ========================================== */}
            <aside id="sidebar-panel" className="w-72 bg-slate-900 flex flex-col border-r border-slate-800 shrink-0">
          <div className="p-5 border-b border-slate-800">
            <div className="flex items-center gap-2 text-blue-400 font-bold text-lg">
              <div className="w-9 h-9 bg-blue-600 rounded-lg flex items-center justify-center text-white shadow-lg shadow-blue-900/30">
                <Database className="w-5 h-5" />
              </div>
              <div className="flex flex-col">
                <span className="leading-tight text-white tracking-tight">Architect SQL</span>
                <span className="text-[10px] text-slate-400 font-mono font-normal">Banking Schema Platform</span>
              </div>
            </div>
          </div>

          <nav className="flex-1 px-4 py-6 overflow-y-auto space-y-6">
            
            {/* Main Tabs */}
            <div>
              <div className="text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-2.5 px-2">System Workspaces</div>
              <ul className="space-y-1">
                <li>
                  <button 
                    onClick={() => setActiveTab('explorer')}
                    className={`w-full flex items-center justify-between px-3 py-2.5 rounded-lg text-sm transition-all ${
                      activeTab === 'explorer' 
                        ? 'bg-blue-600 text-white font-medium shadow-md shadow-blue-900/20' 
                        : 'text-slate-400 hover:text-slate-100 hover:bg-slate-800/60'
                    }`}
                  >
                    <div className="flex items-center gap-2.5">
                      <Table className="w-4 h-4" />
                      <span>Table Schema Explorer</span>
                    </div>
                    <span className="text-[10px] bg-slate-800 text-slate-400 px-1.5 py-0.5 rounded font-mono">9 TBL</span>
                  </button>
                </li>
                <li>
                  <button 
                    onClick={() => setActiveTab('ddl')}
                    className={`w-full flex items-center justify-between px-3 py-2.5 rounded-lg text-sm transition-all ${
                      activeTab === 'ddl' 
                        ? 'bg-blue-600 text-white font-medium shadow-md shadow-blue-900/20' 
                        : 'text-slate-400 hover:text-slate-100 hover:bg-slate-800/60'
                    }`}
                  >
                    <div className="flex items-center gap-2.5">
                      <Code className="w-4 h-4" />
                      <span>PostgreSQL DDL script</span>
                    </div>
                    <span className="text-[10px] bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 px-1.5 py-0.5 rounded font-mono font-bold">init.sql</span>
                  </button>
                </li>
                <li>
                  <button 
                    onClick={() => setActiveTab('ledger')}
                    className={`w-full flex items-center justify-between px-3 py-2.5 rounded-lg text-sm transition-all ${
                      activeTab === 'ledger' 
                        ? 'bg-blue-600 text-white font-medium shadow-md shadow-blue-900/20' 
                        : 'text-slate-400 hover:text-slate-100 hover:bg-slate-800/60'
                    }`}
                  >
                    <div className="flex items-center gap-2.5">
                      <GitCommit className="w-4 h-4" />
                      <span>Immutable Snapshot Ledger</span>
                    </div>
                    <span className="text-[10px] bg-blue-500/10 text-blue-400 border border-blue-500/20 px-1.5 py-0.5 rounded font-mono">{versions.length}</span>
                  </button>
                </li>
                <li>
                  <button 
                    onClick={() => setActiveTab('checklist')}
                    className={`w-full flex items-center justify-between px-3 py-2.5 rounded-lg text-sm transition-all ${
                      activeTab === 'checklist' 
                        ? 'bg-blue-600 text-white font-medium shadow-md shadow-blue-900/20' 
                        : 'text-slate-400 hover:text-slate-100 hover:bg-slate-800/60'
                    }`}
                  >
                    <div className="flex items-center gap-2.5">
                      <ShieldCheck className="w-4 h-4" />
                      <span>Audit Integrity & Compliance</span>
                    </div>
                    {activeUnresolvedQuestionsCount > 0 ? (
                      <span className="text-[10px] bg-amber-500 text-slate-950 px-1.5 py-0.5 rounded font-bold animate-pulse">{activeUnresolvedQuestionsCount} PND</span>
                    ) : (
                      <span className="text-[10px] bg-emerald-500 text-slate-950 px-1.5 py-0.5 rounded font-bold">PASS</span>
                    )}
                  </button>
                </li>
              </ul>
            </div>

            {/* Sub Explorer: Active Tables shortcuts */}
            <div>
              <div className="text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-2.5 px-2">Table Schema Directory</div>
              <ul className="space-y-1 text-xs">
                {TABLES.map((t) => (
                  <li key={t.name}>
                    <button
                      onClick={() => {
                        setSelectedTableName(t.name);
                        setActiveTab('explorer');
                      }}
                      className={`w-full flex items-center justify-between px-3 py-1.5 rounded transition-all ${
                        selectedTableName === t.name && activeTab === 'explorer'
                          ? 'bg-slate-800 text-blue-400 font-semibold'
                          : 'text-slate-400 hover:text-slate-200 hover:bg-slate-800/30'
                      }`}
                    >
                      <div className="flex items-center gap-2">
                        <span className="w-1.5 h-1.5 rounded-full bg-slate-600"></span>
                        <span className="font-mono">{t.name}</span>
                      </div>
                      {t.name === 'version_history' && (
                        <span className="text-[9px] bg-blue-500/20 text-blue-300 font-mono px-1 py-0.1 rounded border border-blue-500/20">JSONB</span>
                      )}
                    </button>
                  </li>
                ))}
              </ul>
            </div>

            {/* Quick Metrics */}
            <div className="bg-slate-950/50 p-4 rounded-xl border border-slate-800 space-y-3">
              <div className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Audit Security Level</div>
              <div className="space-y-1">
                <div className="flex justify-between text-xs text-slate-300">
                  <span>Compliance Rating</span>
                  <span className="font-mono font-bold text-emerald-400">{auditValidityScorePercent}%</span>
                </div>
                <div className="w-full bg-slate-800 h-2 rounded-full overflow-hidden">
                  <div 
                    className="bg-emerald-500 h-full rounded-full transition-all duration-500" 
                    style={{ width: `${auditValidityScorePercent}%` }}
                  ></div>
                </div>
              </div>
              <div className="flex items-center justify-between text-[10px] text-slate-500">
                <span>Total Stories: {userStories.length}</span>
                <span>Audit Lock: {requirements.filter(r => r.is_locked).length} Epic</span>
              </div>
            </div>

          </nav>

          <div className="p-4 border-t border-slate-800 bg-slate-950 text-xs">
            <div className="flex items-center gap-3">
              <div className={`w-2.5 h-2.5 rounded-full ${activeUnresolvedQuestionsCount === 0 ? 'bg-emerald-500' : 'bg-amber-400'} animate-pulse`}></div>
              <div className="flex flex-col">
                <span className="text-slate-300 font-medium">Database Cloud Ready</span>
                <span className="text-[10px] text-slate-500">Fast connection tunnel active</span>
              </div>
            </div>
          </div>
        </aside>

        {/* ==========================================
            MAIN CONTENT SECTION
        ========================================== */}
        <main className="flex-1 flex flex-col overflow-hidden">
          
          {/* HEADER BAR */}
          <header className="h-16 bg-white border-b border-slate-200 flex items-center justify-between px-8 shrink-0">
            <div className="flex flex-col">
              <div className="flex items-center gap-2">
                <h1 className="text-base font-bold text-slate-900 tracking-tight">Enterprise Core Banking</h1>
                <span className="text-[10px] font-mono px-1.5 py-0.5 bg-blue-50 text-blue-700 font-bold border border-blue-200 rounded">v1.2.0-STABLE</span>
              </div>
              <p className="text-xs text-slate-500">Requirements Engineering, Postgres Schema DDL & Snapshot Ledger</p>
            </div>
            
            <div className="flex items-center gap-3">
              <button 
                onClick={copySqlToClipboard}
                className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-slate-700 bg-white border border-slate-300 rounded-lg hover:bg-slate-50 active:bg-slate-100 transition-all cursor-pointer shadow-sm"
              >
                {copiedSql ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copiedSql ? "Copied" : "Copy DDL Code"}</span>
              </button>
              
              <button 
                onClick={() => {
                  setIsSchemaLocked(!isSchemaLocked);
                  showToast(isSchemaLocked ? "Schema unlocked. Sandbox mutations allowed." : "Schema safely locked. Snapshot immutability enforced.", "info");
                }}
                className={`flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold rounded-lg transition-all border shadow-sm ${
                  isSchemaLocked 
                    ? 'bg-emerald-50/50 text-emerald-700 border-emerald-300 hover:bg-emerald-100/50'
                    : 'bg-amber-50/50 text-amber-700 border-amber-300 hover:bg-amber-100/50'
                }`}
              >
                {isSchemaLocked ? <Lock className="w-3.5 h-3.5" /> : <Unlock className="w-3.5 h-3.5" />}
                <span>{isSchemaLocked ? "Schema Locked" : "Schema Unlocked"}</span>
              </button>

              <button 
                onClick={() => {
                  showToast("Initializing schema check... all constraints resolved in 0.2ms. Supabase sync OK.", "success");
                }}
                className="flex items-center gap-1.5 px-4.5 py-1.5 text-xs font-semibold text-white bg-blue-600 rounded-lg hover:bg-blue-700 shadow-md shadow-blue-500/20 active:translate-y-0.5 transition-all"
              >
                <RefreshCw className="w-3.5 h-3.5 animate-spin" style={{ animationDuration: '4s' }} />
                <span>Verify Live Schema</span>
              </button>
            </div>
          </header>

          {/* MAIN TABBED SCROLL CONTAINER */}
          <div className="flex-1 overflow-y-auto p-6 bg-slate-50 flex gap-6">
            
            {/* LEFT AREA: WORKSPACE DISPLAY */}
            <div className="flex-1 flex flex-col gap-6 min-w-0">
              
              {/* ==========================================
                  TAB: POSTGRESQL DDL (init.sql)
              ========================================== */}
              {activeTab === 'ddl' && (
                <div className="flex-1 flex flex-col bg-slate-950 rounded-xl shadow-lg overflow-hidden border border-slate-800">
                  <div className="bg-slate-900 px-5 py-3 border-b border-slate-800 flex justify-between items-center shrink-0">
                    <div className="flex items-center gap-3">
                      <span className="flex w-2.5 h-2.5 rounded-full bg-blue-500"></span>
                      <span className="text-xs font-mono font-bold text-slate-200">init.sql - Postgres DDL</span>
                    </div>
                    <div className="flex items-center gap-3">
                      <div className="relative">
                        <Search className="w-3.5 h-3.5 text-slate-500 absolute left-2.5 top-1/2 transform -translate-y-1/2" />
                        <input 
                          type="text" 
                          placeholder="Search lines or constraints..."
                          value={sqlSearch}
                          onChange={(e) => setSqlSearch(e.target.value)}
                          className="pl-8 pr-3 py-1 bg-slate-950 border border-slate-800 rounded text-xs text-slate-300 font-mono focus:outline-none focus:border-blue-500 w-52 transition-all"
                        />
                      </div>
                      <span className="text-[10px] font-mono text-emerald-400 bg-emerald-950/50 border border-emerald-900 px-2 py-0.5 rounded uppercase">221 Lines</span>
                    </div>
                  </div>
                  
                  <div className="p-5 font-mono text-[12px] leading-relaxed overflow-y-auto flex-1 select-text scrollbar-thin scrollbar-thumb-slate-800">
                    <pre className="text-slate-300 whitespace-pre-wrap">
                      {sqlLines.map((line, i) => {
                        const isObj = typeof line === 'object';
                        const text = isObj ? (line as any).text : line;
                        const highlighted = isObj ? (line as any).highlighted : false;
                        
                        return (
                          <div 
                            key={i} 
                            className={`py-0.5 px-2 rounded -mx-2 flex ${
                              highlighted ? 'bg-amber-500/20 text-white font-bold border-l-2 border-amber-500' : 'hover:bg-slate-900/30'
                            }`}
                          >
                            <span className="text-slate-600 select-none w-8 shrink-0 text-right pr-3 font-mono text-[10px]">{i + 1}</span>
                            <span className="break-all">{text || ' '}</span>
                          </div>
                        );
                      })}
                    </pre>
                  </div>
                  <div className="bg-slate-900 px-5 py-3 border-t border-slate-800 flex justify-between items-center text-xs text-slate-400 font-mono">
                    <span>Target: Supabase PostgreSQL (uuid-ossp enabled)</span>
                    <button 
                      onClick={copySqlToClipboard}
                      className="text-blue-400 hover:text-blue-300 flex items-center gap-1 font-semibold"
                    >
                      <Copy className="w-3.5 h-3.5" />
                      <span>Copy Full DDL Script</span>
                    </button>
                  </div>
                </div>
              )}

              {/* ==========================================
                  TAB: TABLE SCHEMA EXPLORER
              ========================================== */}
              {activeTab === 'explorer' && (
                <div className="flex flex-col gap-6">
                  
                  {/* Table metadata card */}
                  <div className="bg-white rounded-xl border border-slate-200 p-6 shadow-sm">
                    <div className="flex justify-between items-start gap-4">
                      <div>
                        <div className="flex items-center gap-2.5">
                          <div className="w-8 h-8 rounded-lg bg-blue-100 text-blue-600 flex items-center justify-center font-mono font-bold text-sm">
                            T
                          </div>
                          <h2 className="text-lg font-bold text-slate-900 font-mono">
                            {activeTableSchema.name}
                          </h2>
                        </div>
                        <p className="text-sm text-slate-600 mt-2">
                          {activeTableSchema.description}
                        </p>
                      </div>

                      <div className="bg-blue-50 border border-blue-100 p-4 rounded-xl max-w-sm shrink-0">
                        <div className="flex gap-2 items-start">
                          <Activity className="w-4 h-4 text-blue-600 mt-0.5 shrink-0" />
                          <div>
                            <h4 className="text-[11px] font-bold text-blue-900 uppercase tracking-wider">Banking Compliance Purpose</h4>
                            <p className="text-xs text-blue-700 mt-1 leading-relaxed">
                              {activeTableSchema.bankingContext}
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>

                    {/* Table properties list */}
                    <div className="mt-6 border-t border-slate-100 pt-5">
                      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs">
                        <div className="p-3 bg-slate-50 rounded-lg">
                          <span className="text-slate-400 block font-semibold mb-1">Index Setup</span>
                          <div className="font-mono text-[11px] space-y-1">
                            {activeTableSchema.indexes.map((idx, i) => (
                              <div key={i} className="text-slate-700 bg-white px-2 py-0.5 border border-slate-200 rounded">
                                {idx}
                              </div>
                            ))}
                            {activeTableSchema.indexes.length === 0 && (
                              <span className="text-slate-400 italic">PK auto-indexed</span>
                            )}
                          </div>
                        </div>

                        <div className="p-3 bg-slate-50 rounded-lg col-span-2">
                          <span className="text-slate-400 block font-semibold mb-1">Relational Constraints (Foreign Keys)</span>
                          <div className="space-y-1">
                            {activeTableSchema.relations.map((rel, i) => (
                              <div key={i} className="flex items-center gap-2 font-mono text-[11px] text-slate-700 bg-white px-2 py-0.5 border border-slate-200 rounded">
                                <span className="font-bold text-blue-600">{rel.fromColumn}</span>
                                <span>&rarr;</span>
                                <span className="font-bold text-slate-900">{rel.toTable}({rel.toColumn})</span>
                                <span className="ml-auto text-[10px] bg-red-50 text-red-700 px-1.5 py-0.2 rounded border border-red-100 font-bold uppercase">
                                  ON DELETE {rel.onDelete}
                                </span>
                              </div>
                            ))}
                            {activeTableSchema.relations.length === 0 && (
                              <span className="text-slate-400 italic font-sans block">Independent lookup entity (No outbound foreign relations).</span>
                            )}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Datagrid Section */}
                  <div className="bg-white rounded-xl border border-slate-200 overflow-hidden shadow-sm flex flex-col">
                    <div className="bg-slate-50 border-b border-slate-200 px-6 py-4 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                      <div>
                        <h3 className="text-sm font-bold text-slate-900">Live Simulated Ingress Records</h3>
                        <p className="text-xs text-slate-500 mt-0.5">Reflecting current state in client cache</p>
                      </div>
                      
                      <div className="flex items-center gap-2 w-full sm:w-auto">
                        <div className="relative flex-1 sm:flex-initial">
                          <Search className="w-3.5 h-3.5 text-slate-400 absolute left-3 top-1/2 transform -translate-y-1/2" />
                          <input 
                            type="text" 
                            placeholder="Filter grid data..."
                            value={gridSearch}
                            onChange={(e) => setGridSearch(e.target.value)}
                            className="pl-9 pr-3 py-1.5 w-full sm:w-48 bg-white border border-slate-300 rounded-lg text-xs focus:outline-none focus:border-blue-600 transition-colors"
                          />
                        </div>
                        <span className="text-xs font-mono text-slate-500 bg-slate-200 px-2 py-1 rounded font-bold shrink-0">
                          {filteredGridData.length} ROWS
                        </span>
                      </div>
                    </div>

                    <div className="overflow-x-auto">
                      <table className="w-full text-left border-collapse text-xs">
                        <thead>
                          <tr className="bg-slate-50/50 border-b border-slate-200 text-slate-500 font-semibold select-none">
                            <th className="p-3.5 pl-6 font-mono">id (UUID)</th>
                            {activeTableSchema.columns.filter(c => c.name !== 'id').map(c => (
                              <th key={c.name} className="p-3.5">
                                <div className="flex flex-col">
                                  <span className="font-mono text-slate-950">{c.name}</span>
                                  <span className="text-[10px] text-slate-400 font-normal">{c.type}</span>
                                </div>
                              </th>
                            ))}
                            {selectedTableName === 'requirements' && (
                              <th className="p-3.5 text-right pr-6">Lock Status</th>
                            )}
                          </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-100">
                          {filteredGridData.length === 0 ? (
                            <tr>
                              <td colSpan={activeTableSchema.columns.length + 1} className="p-10 text-center text-slate-400 italic">
                                No rows simulated or matching filter. Use the form below to simulate SQL INSERT!
                              </td>
                            </tr>
                          ) : (
                            filteredGridData.map((row: any, rIdx) => (
                              <tr key={row.id || rIdx} className="hover:bg-slate-50/50 transition-colors">
                                <td className="p-3.5 pl-6 font-mono text-blue-600 select-all max-w-[120px] truncate" title={row.id}>
                                  {row.id}
                                </td>
                                {activeTableSchema.columns.filter(c => c.name !== 'id').map(col => {
                                  let val = row[col.name];
                                  if (typeof val === 'object' && val !== null) {
                                    val = JSON.stringify(val);
                                  }
                                  const displayValue = val === true ? 'TRUE' : val === false ? 'FALSE' : val === null || val === undefined ? 'NULL' : String(val);
                                  
                                  return (
                                    <td key={col.name} className="p-3.5 text-slate-700 font-sans max-w-[200px] truncate" title={displayValue}>
                                      {col.name === 'project_id' ? (
                                        <span className="font-mono bg-slate-100 text-slate-700 px-1 py-0.5 rounded text-[10px]" title={val}>
                                          {getProjectName(val)}
                                        </span>
                                      ) : col.name === 'user_id' || col.name === 'changed_by_user_id' ? (
                                        <span className="font-mono bg-slate-100 text-slate-700 px-1 py-0.5 rounded text-[10px]" title={val}>
                                          {getUserName(val)}
                                        </span>
                                      ) : col.name === 'requirement_id' ? (
                                        <span className="font-mono bg-slate-100 text-slate-700 px-1 py-0.5 rounded text-[10px]" title={val}>
                                          {getEpicName(val)}
                                        </span>
                                      ) : col.name === 'state_snapshot' || col.name === 'passed_checks' || col.name === 'failed_checks' ? (
                                        <code className="text-[10px] bg-slate-900 text-slate-300 px-1.5 py-0.5 rounded font-mono truncate block max-w-xs">{displayValue}</code>
                                      ) : (
                                        displayValue
                                      )}
                                    </td>
                                  );
                                })}
                                {selectedTableName === 'requirements' && (
                                  <td className="p-3.5 text-right pr-6">
                                    <button 
                                      onClick={() => toggleEpicLock(row.id)}
                                      className={`px-2 py-1 rounded text-[10px] font-bold ${
                                        row.is_locked 
                                          ? 'bg-amber-100 text-amber-800 hover:bg-amber-200' 
                                          : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
                                      } transition-colors`}
                                    >
                                      {row.is_locked ? "Locked 🔒" : "Unlock 🔓"}
                                    </button>
                                  </td>
                                )}
                              </tr>
                            ))
                          )}
                        </tbody>
                      </table>
                    </div>
                  </div>

                  {/* Interactive Insertion Simulator */}
                  <div className="bg-white rounded-xl border border-slate-200 p-6 shadow-sm">
                    <div className="flex items-center gap-2 mb-4">
                      <Plus className="w-4 h-4 text-blue-600" />
                      <h3 className="text-sm font-bold text-slate-900">
                        Interactive SQL Data Ingress Simulator
                      </h3>
                    </div>
                    <p className="text-xs text-slate-500 mb-6 -mt-3">
                      Simulate a high-precision `INSERT INTO {selectedTableName}` query with full schema type checking.
                    </p>

                    {isSchemaLocked && (
                      <div className="bg-slate-50 border border-slate-200 p-4 rounded-xl flex items-start gap-3 mb-6">
                        <AlertCircle className="w-4.5 h-4.5 text-amber-600 shrink-0 mt-0.5" />
                        <div>
                          <p className="text-xs font-semibold text-slate-800">Schema Ingress Protected</p>
                          <p className="text-[11px] text-slate-500 mt-0.5">
                            The schema protection is locked to safeguard production integrity. Toggle the <strong>"Schema Lock"</strong> in the top header to unlock interactive mutations and simulate custom records!
                          </p>
                        </div>
                      </div>
                    )}

                    {!isSchemaLocked && (
                      <form onSubmit={handleInsertSimulatedRow} className="space-y-4">
                        
                        {/* Selected Table = USERS FORM */}
                        {selectedTableName === 'users' && (
                          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                            <div>
                              <label className="block text-[11px] font-bold text-slate-500 uppercase mb-1">Corporate Email</label>
                              <input 
                                type="email" 
                                required
                                value={userForm.email} 
                                onChange={e => setUserForm({ ...userForm, email: e.target.value })}
                                placeholder="e.g. some.user@krungsri.com"
                                className="w-full bg-white border border-slate-300 rounded-lg p-2 text-xs focus:outline-none focus:border-blue-600"
                              />
                            </div>
                            <div>
                              <label className="block text-[11px] font-bold text-slate-500 uppercase mb-1">Full Name</label>
                              <input 
                                type="text" 
                                required
                                value={userForm.fullName} 
                                onChange={e => setUserForm({ ...userForm, fullName: e.target.value })}
                                placeholder="e.g. Kittipong Wang"
                                className="w-full bg-white border border-slate-300 rounded-lg p-2 text-xs focus:outline-none focus:border-blue-600"
                              />
                            </div>
                            <div>
                              <label className="block text-[11px] font-bold text-slate-500 uppercase mb-1">RBAC Role</label>
                              <select 
                                value={userForm.role}
                                onChange={e => setUserForm({ ...userForm, role: e.target.value })}
                                className="w-full bg-white border border-slate-300 rounded-lg p-2 text-xs focus:outline-none focus:border-blue-600"
                              >
                                <option value="Product Owner">Product Owner</option>
                                <option value="Business Analyst">Business Analyst</option>
                                <option value="Regulatory Auditor">Regulatory Auditor</option>
                                <option value="Lead Developer">Lead Developer</option>
                              </select>
                            </div>
                          </div>
                        )}

                        {/* Selected Table = PROJECTS FORM */}
                        {selectedTableName === 'projects' && (
                          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div>
                              <label className="block text-[11px] font-bold text-slate-500 uppercase mb-1">Project Name</label>
                              <input 
                                type="text" 
                                required
                                value={projectForm.name} 
                                onChange={e => setProjectForm({ ...projectForm, name: e.target.value })}
                                placeholder="e.g. Nimble Core Mobile API"
                                className="w-full bg-white border border-slate-300 rounded-lg p-2 text-xs focus:outline-none focus:border-blue-600"
                              />
                            </div>
                            <div>
                              <label className="block text-[11px] font-bold text-slate-500 uppercase mb-1">Target Analyst (user_id)</label>
                              <select 
                                value={projectForm.userId}
                                onChange={e => setProjectForm({ ...projectForm, userId: e.target.value })}
                                className="w-full bg-white border border-slate-300 rounded-lg p-2 text-xs focus:outline-none focus:border-blue-600"
                              >
                                {users.map(u => (
                                  <option key={u.id} value={u.id}>{u.full_name} ({u.role})</option>
                                ))}
                              </select>
                            </div>
                            <div className="md:col-span-2">
                              <label className="block text-[11px] font-bold text-slate-500 uppercase mb-1">System Scope Description</label>
                              <textarea 
                                value={projectForm.description} 
                                onChange={e => setProjectForm({ ...projectForm, description: e.target.value })}
                                placeholder="Provide enterprise banking scope definitions..."
                                className="w-full bg-white border border-slate-300 rounded-lg p-2 text-xs focus:outline-none focus:border-blue-600 h-16"
                              />
                            </div>
                          </div>
                        )}

                        {/* Selected Table = REQUIREMENTS FORM */}
                        {selectedTableName === 'requirements' && (
                          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div>
                              <label className="block text-[11px] font-bold text-slate-500 uppercase mb-1">Epic Scope Name</label>
                              <input 
                                type="text" 
                                required
                                value={reqForm.epicName} 
                                onChange={e => setReqForm({ ...reqForm, epicName: e.target.value })}
                                placeholder="e.g. Biometric Face Matcher API"
                                className="w-full bg-white border border-slate-300 rounded-lg p-2 text-xs focus:outline-none focus:border-blue-600"
                              />
                            </div>
                            <div>
                              <label className="block text-[11px] font-bold text-slate-500 uppercase mb-1">Parent Project (project_id)</label>
                              <select 
                                value={reqForm.projectId}
                                onChange={e => setReqForm({ ...reqForm, projectId: e.target.value })}
                                className="w-full bg-white border border-slate-300 rounded-lg p-2 text-xs focus:outline-none focus:border-blue-600"
                              >
                                {projects.map(p => (
                                  <option key={p.id} value={p.id}>{p.name}</option>
                                ))}
                              </select>
                            </div>
                          </div>
                        )}

                        {/* Selected Table = USER STORIES FORM */}
                        {selectedTableName === 'user_stories' && (
                          <div className="space-y-4">
                            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                              <div>
                                <label className="block text-[11px] font-bold text-slate-500 uppercase mb-1">Epic Grouping (requirement_id)</label>
                                <select 
                                  value={storyForm.requirementId}
                                  onChange={e => setStoryForm({ ...storyForm, requirementId: e.target.value })}
                                  className="w-full bg-white border border-slate-300 rounded-lg p-2 text-xs focus:outline-none focus:border-blue-600"
                                >
                                  {requirements.map(r => (
                                    <option key={r.id} value={r.id}>{r.epic_name}</option>
                                  ))}
                                </select>
                              </div>
                              <div>
                                <label className="block text-[11px] font-bold text-slate-500 uppercase mb-1">Agile Ticket Code</label>
                                <input 
                                  type="text" 
                                  required
                                  value={storyForm.ticketCode} 
                                  onChange={e => setStoryForm({ ...storyForm, ticketCode: e.target.value })}
                                  placeholder="e.g. US-PAY-004"
                                  className="w-full bg-white border border-slate-300 rounded-lg p-2 text-xs focus:outline-none focus:border-blue-600"
                                />
                              </div>
                              <div>
                                <label className="block text-[11px] font-bold text-slate-500 uppercase mb-1">Story Descriptive Title</label>
                                <input 
                                  type="text" 
                                  required
                                  value={storyForm.storyTitle} 
                                  onChange={e => setStoryForm({ ...storyForm, storyTitle: e.target.value })}
                                  placeholder="e.g. Biometric Fallback Authentication"
                                  className="w-full bg-white border border-slate-300 rounded-lg p-2 text-xs focus:outline-none focus:border-blue-600"
                                />
                              </div>
                            </div>

                            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                              <div>
                                <label className="block text-[11px] font-bold text-slate-500 uppercase mb-1">As a...</label>
                                <textarea 
                                  required
                                  value={storyForm.asA} 
                                  onChange={e => setStoryForm({ ...storyForm, asA: e.target.value })}
                                  placeholder="e.g. Retail bank client with locked credentials"
                                  className="w-full bg-white border border-slate-300 rounded-lg p-2 text-xs focus:outline-none focus:border-blue-600 h-16"
                                />
                              </div>
                              <div>
                                <label className="block text-[11px] font-bold text-slate-500 uppercase mb-1">I want to...</label>
                                <textarea 
                                  required
                                  value={storyForm.iWantTo} 
                                  onChange={e => setStoryForm({ ...storyForm, iWantTo: e.target.value })}
                                  placeholder="e.g. authenticate utilizing my verified device's secure enclave biometric keys"
                                  className="w-full bg-white border border-slate-300 rounded-lg p-2 text-xs focus:outline-none focus:border-blue-600 h-16"
                                />
                              </div>
                              <div>
                                <label className="block text-[11px] font-bold text-slate-500 uppercase mb-1">So that...</label>
                                <textarea 
                                  required
                                  value={storyForm.soThat} 
                                  onChange={e => setStoryForm({ ...storyForm, soThat: e.target.value })}
                                  placeholder="e.g. I can perform transaction limits overrides without needing phone-support calls."
                                  className="w-full bg-white border border-slate-300 rounded-lg p-2 text-xs focus:outline-none focus:border-blue-600 h-16"
                                />
                              </div>
                            </div>

                            <div className="bg-blue-50/50 p-4 rounded-xl border border-blue-100">
                              <label className="block text-[11px] font-bold text-slate-700 uppercase mb-1">
                                Optional: Append Acceptance Criteria block (Automated transactional insertion)
                              </label>
                              <textarea 
                                value={storyForm.criteriaText} 
                                onChange={e => setStoryForm({ ...storyForm, criteriaText: e.target.value })}
                                placeholder="GIVEN the customer faces credential failure&#10;WHEN they select face verification&#10;THEN the mobile client queries secure local hardware match..."
                                className="w-full bg-white border border-slate-300 rounded-lg p-2 text-xs focus:outline-none focus:border-blue-600 h-20 font-mono"
                              />
                            </div>
                          </div>
                        )}

                        {/* Read-only Tables info */}
                        {(selectedTableName === 'acceptance_criteria' || 
                          selectedTableName === 'audit_results' || 
                          selectedTableName === 'clarification_questions' || 
                          selectedTableName === 'prd_documents' || 
                          selectedTableName === 'version_history') && (
                          <div className="bg-slate-50 text-slate-600 p-4 rounded-lg text-xs italic">
                            Mutations on <strong>{selectedTableName}</strong> are automatically triggered by regulatory checking routines, system audits, or snapshot creation to maintain professional state-machine integrity. Use the corresponding dedicated widgets for these tables!
                          </div>
                        )}

                        <div className="flex justify-end pt-2">
                          {!(selectedTableName === 'acceptance_criteria' || 
                            selectedTableName === 'audit_results' || 
                            selectedTableName === 'clarification_questions' || 
                            selectedTableName === 'prd_documents' || 
                            selectedTableName === 'version_history') && (
                            <button
                              type="submit"
                              className="px-4.5 py-2 bg-slate-900 text-white rounded-lg hover:bg-slate-800 transition-colors text-xs font-semibold flex items-center gap-1.5 cursor-pointer shadow"
                            >
                              <Plus className="w-4 h-4" />
                              <span>Execute Simulated SQL Insert</span>
                            </button>
                          )}
                        </div>

                      </form>
                    )}
                  </div>

                </div>
              )}

              {/* ==========================================
                  TAB: IMMUTABLE VERSION SNAPSHOT LEDGER
              ========================================== */}
              {activeTab === 'ledger' && (
                <div className="space-y-6">
                  
                  <div className="bg-white rounded-xl border border-slate-200 p-6 shadow-sm">
                    <h3 className="text-sm font-bold text-slate-900 mb-2">Immutable JSONB State Snapshot Capture</h3>
                    <p className="text-xs text-slate-500 mb-6">
                      Agile requirements are prone to scope-creep and audit failures. In accordance with compliance models, the system forces a deep snapshot export on each approved iteration.
                    </p>

                    <form onSubmit={handleCaptureSnapshot} className="space-y-4">
                      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                        <div>
                          <label className="block text-[11px] font-bold text-slate-500 uppercase mb-1">Target Epic (requirement_id)</label>
                          <select 
                            value={snapshotForm.requirementId}
                            onChange={e => setSnapshotForm({ ...snapshotForm, requirementId: e.target.value })}
                            className="w-full bg-white border border-slate-300 rounded-lg p-2 text-xs focus:outline-none focus:border-blue-600"
                          >
                            {requirements.map(r => (
                              <option key={r.id} value={r.id}>{r.epic_name} (v{r.current_version})</option>
                            ))}
                          </select>
                        </div>
                        <div>
                          <label className="block text-[11px] font-bold text-slate-500 uppercase mb-1">Authorized Author (changed_by)</label>
                          <select 
                            value={snapshotForm.authorId}
                            onChange={e => setSnapshotForm({ ...snapshotForm, authorId: e.target.value })}
                            className="w-full bg-white border border-slate-300 rounded-lg p-2 text-xs focus:outline-none focus:border-blue-600"
                          >
                            {users.map(u => (
                              <option key={u.id} value={u.id}>{u.full_name} ({u.role})</option>
                            ))}
                          </select>
                        </div>
                        <div>
                          <label className="block text-[11px] font-bold text-slate-500 uppercase mb-1">Capture Action</label>
                          <button
                            type="submit"
                            className="w-full py-2 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-lg text-xs flex items-center justify-center gap-1.5 transition-colors cursor-pointer shadow shadow-blue-500/20"
                          >
                            <GitCommit className="w-4 h-4" />
                            <span>Capture State Snapshot</span>
                          </button>
                        </div>
                      </div>

                      <div>
                        <label className="block text-[11px] font-bold text-slate-500 uppercase mb-1">Change Control Log & Description</label>
                        <input 
                          type="text" 
                          required
                          value={snapshotForm.changeDescription}
                          onChange={e => setSnapshotForm({ ...snapshotForm, changeDescription: e.target.value })}
                          placeholder="e.g., Aligned criteria with national clearing thresholds and added fallback loops."
                          className="w-full bg-white border border-slate-300 rounded-lg p-2.5 text-xs focus:outline-none focus:border-blue-600"
                        />
                      </div>
                    </form>
                  </div>

                  {/* Historical logs render */}
                  <div className="bg-white rounded-xl border border-slate-200 p-6 shadow-sm">
                    <h3 className="text-sm font-bold text-slate-900 mb-4">Immutable Ledger History (version_history table)</h3>
                    
                    <div className="space-y-4">
                      {versions.map((ver, idx) => {
                        const snap = JSON.parse(ver.state_snapshot);
                        return (
                          <div key={ver.id} className="border border-slate-200 rounded-xl overflow-hidden shadow-sm">
                            <div className="bg-slate-50 px-4 py-3 border-b border-slate-200 flex justify-between items-center text-xs">
                              <div className="flex items-center gap-2">
                                <span className="font-mono bg-blue-50 text-blue-700 border border-blue-200 px-2 py-0.5 rounded font-bold uppercase">
                                  VERSION {ver.version_number}.0
                                </span>
                                <span className="text-slate-400 font-mono">|</span>
                                <span className="font-sans text-slate-600 font-semibold">Epic: {getEpicName(ver.requirement_id)}</span>
                              </div>
                              <span className="font-mono text-slate-400 text-[11px]">
                                Posted: {ver.created_at}
                              </span>
                            </div>

                            <div className="p-4 grid grid-cols-1 md:grid-cols-3 gap-4 text-xs">
                              <div className="md:col-span-2 space-y-2">
                                <div>
                                  <span className="text-[10px] font-bold text-slate-400 uppercase block">Log Entry Description</span>
                                  <p className="text-slate-800 font-medium">{ver.change_description}</p>
                                </div>
                                <div className="grid grid-cols-2 gap-4 pt-1">
                                  <div>
                                    <span className="text-[10px] font-bold text-slate-400 uppercase block">Project Context</span>
                                    <p className="text-slate-700 font-medium">{getProjectName(ver.project_id)}</p>
                                  </div>
                                  <div>
                                    <span className="text-[10px] font-bold text-slate-400 uppercase block">Committed By</span>
                                    <p className="text-slate-700 font-medium">{getUserName(ver.changed_by_user_id)}</p>
                                  </div>
                                </div>
                              </div>

                              <div className="bg-slate-950 p-3.5 rounded-lg border border-slate-800 font-mono text-[10px] text-slate-300">
                                <span className="text-[9px] text-blue-400 font-bold uppercase block mb-1">Postgres JSONB State</span>
                                <pre className="max-h-24 overflow-y-auto overflow-x-hidden whitespace-pre-wrap leading-tight text-slate-400">
                                  {JSON.stringify(snap, null, 2)}
                                </pre>
                              </div>
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  </div>

                </div>
              )}

              {/* ==========================================
                  TAB: AUDIT INTEGRITY & COMPLIANCE
              ========================================== */}
              {activeTab === 'checklist' && (
                <div className="space-y-6">
                  
                  {/* Compliance overview blocks */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div className="bg-white rounded-xl border border-slate-200 p-6 shadow-sm">
                      <div className="flex items-center gap-3 mb-3">
                        <div className="w-10 h-10 rounded-full bg-emerald-100 text-emerald-600 flex items-center justify-center">
                          <ShieldCheck className="w-5 h-5" />
                        </div>
                        <div>
                          <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider">PostgreSQL Structural Rigor</h4>
                          <h3 className="text-sm font-bold text-slate-900 mt-0.5">Automated DDL Rule Checks</h3>
                        </div>
                      </div>
                      
                      <ul className="space-y-3.5 text-xs pt-2">
                        <li className="flex items-start gap-3">
                          <Check className="w-4 h-4 text-emerald-600 mt-0.5 shrink-0" />
                          <div>
                            <span className="font-bold text-slate-800">UUID v4 Primary Keys (gen_random_uuid())</span>
                            <p className="text-slate-500 text-[11px] mt-0.5">Verified on all 9 tables. Eliminates centralized ID bottleneck sequence leaks.</p>
                          </div>
                        </li>
                        <li className="flex items-start gap-3">
                          <Check className="w-4 h-4 text-emerald-600 mt-0.5 shrink-0" />
                          <div>
                            <span className="font-bold text-slate-800">High-Precision Audit TIMESTAMPTZ Trails</span>
                            <p className="text-slate-500 text-[11px] mt-0.5">Enforces localized time integrity on modified records across the financial network.</p>
                          </div>
                        </li>
                        <li className="flex items-start gap-3">
                          <Check className="w-4 h-4 text-emerald-600 mt-0.5 shrink-0" />
                          <div>
                            <span className="font-bold text-slate-800">Cascading Deletion Rules (CASCADE / RESTRICT)</span>
                            <p className="text-slate-500 text-[11px] mt-0.5">RESTRICT prevents users or projects from deletion if they have active transaction logs.</p>
                          </div>
                        </li>
                      </ul>
                    </div>

                    <div className="bg-white rounded-xl border border-slate-200 p-6 shadow-sm">
                      <div className="flex items-center gap-3 mb-3">
                        <div className="w-10 h-10 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center">
                          <Activity className="w-5 h-5" />
                        </div>
                        <div>
                          <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider">Index Coverage Performance</h4>
                          <h3 className="text-sm font-bold text-slate-900 mt-0.5">Foreign Key Query Optimizers</h3>
                        </div>
                      </div>

                      <ul className="space-y-3.5 text-xs pt-2">
                        <li className="flex items-start gap-3">
                          <Check className="w-4 h-4 text-emerald-600 mt-0.5 shrink-0" />
                          <div>
                            <span className="font-bold text-slate-800">Foreign Key Constraint Coverage</span>
                            <p className="text-slate-500 text-[11px] mt-0.5">11 indexes explicitly generated on foreign keys to prevent full table scans during JOIN queries.</p>
                          </div>
                        </li>
                        <li className="flex items-start gap-3">
                          <Check className="w-4 h-4 text-emerald-600 mt-0.5 shrink-0" />
                          <div>
                            <span className="font-bold text-slate-800">Dashboard Metrics Optimization</span>
                            <p className="text-slate-500 text-[11px] mt-0.5">Indices on columns `is_locked`, `role`, and `is_resolved` maximize throughput under heavy analytical query loads.</p>
                          </div>
                        </li>
                        <li className="flex items-start gap-3">
                          <Check className="w-4 h-4 text-emerald-600 mt-0.5 shrink-0" />
                          <div>
                            <span className="font-bold text-slate-800">Double-Entry Ledger Architecture Check</span>
                            <p className="text-slate-500 text-[11px] mt-0.5">Immutable snapshots logged as standard JSONB blocks ensure absolute audit compliance.</p>
                          </div>
                        </li>
                      </ul>
                    </div>
                  </div>

                  {/* Stakeholder Clarification Questions (interactive resolver) */}
                  <div className="bg-white rounded-xl border border-slate-200 p-6 shadow-sm">
                    <div className="flex items-center justify-between mb-4">
                      <div className="flex items-center gap-2">
                        <HelpCircle className="w-4.5 h-4.5 text-blue-600" />
                        <h3 className="text-sm font-bold text-slate-900">Stakeholder Clarification & Compliance Dialogues</h3>
                      </div>
                      <span className="text-xs bg-slate-100 px-2 py-0.5 rounded font-mono font-bold text-slate-600">
                        clarification_questions table
                      </span>
                    </div>
                    <p className="text-xs text-slate-500 mb-6">
                      Pending queries must be answered and resolved by Product Owners or compliance analysts before core systems are unlocked for production deployment.
                    </p>

                    <div className="space-y-4">
                      {questions.map((q) => (
                        <div key={q.id} className={`p-4 rounded-xl border transition-all ${
                          q.is_resolved 
                            ? 'bg-slate-50/50 border-slate-200' 
                            : 'bg-amber-50/30 border-amber-200'
                        }`}>
                          <div className="flex justify-between items-start gap-4">
                            <div className="space-y-1">
                              <div className="flex items-center gap-2">
                                <span className={`w-2 h-2 rounded-full ${q.is_resolved ? 'bg-slate-400' : 'bg-amber-500 animate-pulse'}`}></span>
                                <span className="text-[10px] font-mono text-slate-400 font-bold uppercase">{q.checklist_category}</span>
                                <span className="text-slate-300">|</span>
                                <span className="text-[10px] font-mono text-slate-500">Story Target: {q.target_user_story_id ? 'US-PAY-002' : 'General'}</span>
                              </div>
                              <p className="text-xs font-semibold text-slate-800 leading-relaxed">
                                {q.question_text}
                              </p>
                            </div>

                            <span className={`px-2 py-0.5 rounded text-[10px] font-bold shrink-0 uppercase tracking-wider ${
                              q.is_resolved 
                                ? 'bg-slate-200 text-slate-600' 
                                : 'bg-amber-100 text-amber-800'
                            }`}>
                              {q.is_resolved ? 'Resolved' : 'Pending Action'}
                            </span>
                          </div>

                          <div className="mt-3.5 border-t border-slate-100 pt-3 text-xs">
                            {q.is_resolved ? (
                              <div className="bg-white p-3 rounded-lg border border-slate-200 text-slate-700">
                                <span className="text-[10px] font-bold text-slate-400 uppercase block mb-1">Official Resolution Response</span>
                                {q.user_answer}
                              </div>
                            ) : (
                              <div>
                                {resolvingQuestionId === q.id ? (
                                  <form onSubmit={(e) => submitQuestionAnswer(e, q.id)} className="flex gap-2">
                                    <input 
                                      type="text" 
                                      required
                                      value={answerInput}
                                      onChange={e => setAnswerInput(e.target.value)}
                                      placeholder="Type official compliance solution..."
                                      className="flex-1 bg-white border border-slate-300 rounded-lg px-3 py-1.5 text-xs focus:outline-none focus:border-blue-600"
                                    />
                                    <button 
                                      type="submit"
                                      className="px-3.5 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-bold flex items-center justify-center gap-1.5 transition-colors cursor-pointer text-xs"
                                    >
                                      <Send className="w-3.5 h-3.5" />
                                      <span>Resolve</span>
                                    </button>
                                  </form>
                                ) : (
                                  <button 
                                    onClick={() => {
                                      setResolvingQuestionId(q.id);
                                      setAnswerInput('');
                                    }}
                                    className="px-3 py-1 bg-amber-500 hover:bg-amber-600 text-slate-950 font-bold rounded-lg transition-colors text-[11px] cursor-pointer"
                                  >
                                    Answer and Lock Compliance
                                  </button>
                                )}
                              </div>
                            )}
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>

                </div>
              )}

            </div>

            {/* RIGHT PANEL: AUDIT SIDE BAR VIEW */}
            <div className="w-80 shrink-0 flex flex-col gap-6">
              
              {/* Card 1: Static DDL Validation Highlights */}
              <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-sm">
                <div className="flex items-center justify-between mb-4 pb-3 border-b border-slate-100">
                  <h3 className="text-xs font-bold text-slate-500 uppercase tracking-widest">Audit Checklist</h3>
                  <span className="text-[10px] bg-slate-100 text-slate-600 font-bold px-1.5 py-0.5 rounded font-mono">DATA</span>
                </div>
                
                <div className="space-y-4">
                  <div className="flex items-start gap-3">
                    <div className="mt-1 w-4 h-4 bg-emerald-100 text-emerald-600 rounded-full flex items-center justify-center shrink-0">
                      <Check className="w-2.5 h-2.5 stroke-[4]" />
                    </div>
                    <div>
                      <p className="text-xs font-semibold text-slate-800">Supabase UUID v4</p>
                      <p className="text-[10px] text-slate-500">All primary keys utilize gen_random_uuid() for identity isolation.</p>
                    </div>
                  </div>
                  
                  <div className="flex items-start gap-3">
                    <div className="mt-1 w-4 h-4 bg-emerald-100 text-emerald-600 rounded-full flex items-center justify-center shrink-0">
                      <Check className="w-2.5 h-2.5 stroke-[4]" />
                    </div>
                    <div>
                      <p className="text-xs font-semibold text-slate-800">Timezone Integrity</p>
                      <p className="text-[10px] text-slate-500">TIMESTAMPTZ explicitly configured to support cross-timezone auditing.</p>
                    </div>
                  </div>
                  
                  <div className="flex items-start gap-3">
                    <div className="mt-1 w-4 h-4 bg-emerald-100 text-emerald-600 rounded-full flex items-center justify-center shrink-0">
                      <Check className="w-2.5 h-2.5 stroke-[4]" />
                    </div>
                    <div>
                      <p className="text-xs font-semibold text-slate-800">Cascade Constraint Locks</p>
                      <p className="text-[10px] text-slate-500">Safe restrict hooks prevent deleting active authors on requirement iterations.</p>
                    </div>
                  </div>

                  <div className="flex items-start gap-3">
                    <div className="mt-1 w-4 h-4 bg-emerald-100 text-emerald-600 rounded-full flex items-center justify-center shrink-0">
                      <Check className="w-2.5 h-2.5 stroke-[4]" />
                    </div>
                    <div>
                      <p className="text-xs font-semibold text-slate-800">Schema Index Coverage</p>
                      <p className="text-[10px] text-slate-500">Indexes generated on all Foreign Keys to guarantee lookup performance.</p>
                    </div>
                  </div>
                </div>
              </div>

              {/* Card 2: Micro Version History Snapshot ledger */}
              <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-sm flex-1 flex flex-col min-h-0">
                <div className="flex items-center justify-between mb-4 pb-3 border-b border-slate-100 shrink-0">
                  <h3 className="text-xs font-bold text-slate-500 uppercase tracking-widest">Version Ledger</h3>
                  <button 
                    onClick={() => setActiveTab('ledger')}
                    className="text-[10px] font-bold text-blue-600 uppercase hover:underline"
                  >
                    View All
                  </button>
                </div>

                <div className="space-y-3.5 overflow-y-auto flex-1 pr-1 scrollbar-thin">
                  {versions.slice(0, 3).map((v, i) => (
                    <div key={v.id} className={`p-3 rounded-lg border text-xs ${i === 0 ? 'bg-slate-50/70 border-slate-100' : 'bg-white border-slate-100'}`}>
                      <div className="flex justify-between items-center mb-1">
                        <span className="text-[10px] font-mono text-blue-600 font-bold uppercase">
                          Version {v.version_number}.0
                        </span>
                        <span className="text-[10px] text-slate-400">
                          {v.created_at.split('T')[1]?.substring(0,5) || '14:20'}
                        </span>
                      </div>
                      <p className="text-[11px] text-slate-700 leading-relaxed font-medium">
                        {v.change_description}
                      </p>
                      <div className="mt-2 flex items-center justify-between text-[9px] text-slate-400">
                        <span>Epic: {getEpicName(v.requirement_id)}</span>
                        <span>Author: {getUserName(v.changed_by_user_id).split(' ')[0]}</span>
                      </div>
                    </div>
                  ))}
                </div>

                <div className="pt-4 mt-auto border-t border-slate-100 text-center shrink-0">
                  <button 
                    onClick={() => {
                      setActiveTab('ledger');
                      showToast("Navigate to Snapshot Ledger Workspace.", "info");
                    }}
                    className="text-[10px] font-bold text-blue-600 uppercase tracking-tight hover:underline flex items-center justify-center gap-1 w-full"
                  >
                    <span>View Immutable Snapshots</span>
                    <ChevronRight className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>

            </div>

          </div>

          {/* BOTTOM STATUS BAR */}
          <footer className="h-10 bg-slate-100 border-t border-slate-200 flex items-center px-6 gap-8 shrink-0 select-none text-[10px]">
            <div className="flex items-center gap-2">
              <span className="font-bold text-slate-400 uppercase">Status</span>
              {activeUnresolvedQuestionsCount === 0 ? (
                <span className="font-bold px-1.5 py-0.5 bg-emerald-100 text-emerald-800 rounded">VALIDATED</span>
              ) : (
                <span className="font-bold px-1.5 py-0.5 bg-amber-100 text-amber-800 rounded animate-pulse">ACTION REQUIRED</span>
              )}
            </div>
            
            <div className="ml-auto flex items-center gap-6">
              <div className="text-slate-500 font-bold">
                Schema Lock: <span className={isSchemaLocked ? "text-emerald-600" : "text-amber-500"}>{isSchemaLocked ? "ON" : "OFF"}</span>
              </div>
            </div>
          </footer>

        </main>
          </>
        )}
      </div>
    </div>
  );
}
